name: zeed
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'  # Remove this line if you want to publish to pub.dev

# Version and build number for the application
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  animations: ^2.0.11
  flutter_riverpod: ^2.0.0
  table_calendar: ^3.1.1 # Add this line
  url_launcher: ^6.3.0 # Add this line for Help/Support
  http: ^1.0.0
  shared_preferences: ^2.0.0
  logging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets section if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Add fonts section if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
